### PR TITLE
Added 2 dependencies

### PR DESCRIPTION
**Pull request by sikhapentyala**
We have added custom dependency federated-fraud-detection with version 0.1.0.
We will update the package to a version 1.0.0 before Jan 25th. 
We hope that the updated version could be added as dependency and used for evaluation then.

### CODE REVIEW

**Comment by jayqi** [comment]
Hi @sikhapentyala,

Is the `federated-fraud-detection` the code for your solution? If so, rather than adding it as a dependency to the runtime image, which is shared for all teams, you may want to vendor it in your submission instead.

**Comment by jayqi** [comment]
Hi @sikhapentyala,

Just checking to see if you have any additional questions. As mentioned before, I recommend not adding your `federated-fraud-detection` library as part of the image and instead uploading it with your submission.

We can probably get `dp-xgboost` in if that is something you need.

**Comment by jellevos** [comment]
Hey @jayqi, I am on the same team as Sikha, and I have been experimenting today with vendoring in the submission code, but I cannot get it to work. Could you point me to a resource to explain how to do this using conda environments? I can get things to run with pip quite easily, but I cannot figure out how to do it here. The dependency is just one wheel (I think this one https://files.pythonhosted.org/packages/ae/a5/0845f3b91f37d53323c5b93a0ac80bf40f95478c6c85f211bc623ea88254/federated_fraud_detection-0.8.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl). Thanks for your help!

**Comment by jayqi** [comment]
Hi @jellevos and @sikhapentyala,

There are a few options of things to try.

Given that you have built a wheel from your code, you may be able to bundle it with your submission and `pip install` it. See [this documentation](https://www.drivendata.org/competitions/105/nist-federated-learning-2-financial-crime-federated/page/587/#optional-install-sh-script) about the optional `install.sh` script where you can do the installation. Note that the runtime uses a conda environment named `condaenv`, so you may need to do something like 

```bash
conda run -n condaenv pip install <path to your wheel>
```

Please note that during runtime, containers will not have internet access, so any dependencies either already be installed in the environment or additionally included and installed.

---

Another option is to vendor your code, which is just including all necessary source files alongside your `solution_federated.py` and `solution_centralized.py` modules in a way that can be imported. You need to make sure that the code is findable on the Python module search path. Here are some references that might be useful: [official docs](https://docs.python.org/3/library/sys_path_init.html), [realpython](https://realpython.com/lessons/module-search-path/)

Let me know if you need additional clarification.

**Comment by jellevos** [comment]
Thanks @jayqi! Your first suggestion works locally for me in the Docker container. I suggest that we first test it as an actual submission before closing this PR. 😄

**Pull request closed without merging**
