### PR TITLE
Add Go package dependency

### PR DESCRIPTION
**Pull request by dinvlad**
This PR adds [Go programming language](https://anaconda.org/conda-forge/go) dependency.

### CODE REVIEW

**Comment by jayqi** [comment]
Hi @dinvlad,

I'm assuming that this PR is related to the conversation on the forums: https://community.drivendata.org/t/calling-golang-from-python/8404

Is it necessary to add Golang to the runtime environment? My understanding is that you wouldn't need it to run precompiled binaries.

**Comment by dinvlad** [comment]
Hi @jayqi, thank you for the follow-up. If it's OK with you, we'd like to include it just in case we run into any issues with a pre-compiled binary, and end up needing this dependency, since we did not have a chance to fully test with the precompiled binaries yet.

**Review by jayqi — APPROVED** [review]
Hi @dinvlad,

I'm going to hold off on merging this for the moment. I expect that it will likely be easier for your team to precompile Go binaries and that approach should work. In that case, it would be nice to keep the runtime image lighter weight.

That said, I'm otherwise fine with this inclusion and we can merge it any time if you conclude that it would be better to be able to compile your code during runtime. This counts as being in before the deadline, so no worries there.

**Comment by dinvlad** [comment]
@jayqi that sounds like a good plan, thanks!

**Comment by jayqi** [comment]
Hi @dinvlad, just checking in to see if packing a Go binary has been working, or if we need to revisit adding Go to the runtime image.

**Comment by dinvlad** [comment]
Thanks for checking back, @jayqi ! I think it's been working ok so far, but we'll be doing more testing tomorrow.

**Comment by jayqi** [comment]
It sounds like this is working, so closing this PR for now.

**Pull request closed without merging**
